'use client';

import { Cloud, Copy, History, RefreshCw, UploadCloud, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { EditorDocument } from '../../domain/document';
import { announceCloudCode, CLOUD_ASSET_PROGRESS_EVENT, CLOUD_CODE_STORAGE_KEY, cloudDocumentCodeKey, hydrateDocumentAssets, uploadDocumentAssets } from '../../infrastructure/collaboration-service';
import { createCloudRoom, loadCloudRoom, loadCloudVersion, pushCloudRoom, type CloudSnapshot } from '../../infrastructure/cloud-sync';

export function CloudSyncDialog({ open, document, onChange, onClose }: { open: boolean; document: EditorDocument; onChange: (document: EditorDocument) => void; onClose: () => void }) {
  const [code, setCode] = useState(() => { try { return new URLSearchParams(location.search).get('share') || localStorage.getItem(cloudDocumentCodeKey(document.id)) || localStorage.getItem(CLOUD_CODE_STORAGE_KEY) || ''; } catch { return ''; } }); const [snapshot, setSnapshot] = useState<CloudSnapshot>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false);
  const [progress, setProgress] = useState<{ name: string; loaded: number; total: number; status: string }>();
  useEffect(() => { const receive = (event: Event) => setProgress((event as CustomEvent<{ name: string; loaded: number; total: number; status: string }>).detail); addEventListener(CLOUD_ASSET_PROGRESS_EVENT, receive); return () => removeEventListener(CLOUD_ASSET_PROGRESS_EVENT, receive); }, []);
  const run = async (action: () => Promise<void>) => { setBusy(true); setMessage(''); setFailed(false); try { await action(); } catch (error) { const conflict = error as Error & { latest?: CloudSnapshot }; if (conflict.latest) setSnapshot(conflict.latest); setFailed(true); setMessage(conflict.message || '요청이 실패했습니다.'); } finally { setBusy(false); } };
  const remember = (value: string) => { setCode(value); if (value) announceCloudCode(value, document.id); };
  const refresh = async (apply = false) => { const value = code.trim(); const next = await loadCloudRoom(value); setSnapshot(next); const assets = apply ? await hydrateDocumentAssets(value, next.document) : { downloaded: 0, missing: 0 }; if (apply) { announceCloudCode(value, next.document.id); onChange(next.document); } setMessage(apply ? `클라우드 ${next.revision}판과 첨부 ${assets.downloaded}개를 적용했습니다${assets.missing ? ` · R2에 없는 첨부 ${assets.missing}개` : ''}.` : `클라우드 ${next.revision}판을 확인했습니다.`); };
  if (!open) return null;
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="dialog cloud-dialog" role="dialog" aria-modal="true" aria-labelledby="cloud-title">
    <header><div><span className="dialog-icon"><Cloud size={20} /></span><span><h2 id="cloud-title">클라우드 동기화·버전·공동 편집</h2><p>공유 코드를 가진 사람끼리 저장하고 충돌을 확인합니다.</p></span></div><button type="button" onClick={onClose} aria-label="닫기"><X /></button></header>
    <div className="dialog-form"><p className="notice warning">공유 코드는 문서와 R2 첨부 파일의 편집 권한을 가진 비밀 링크입니다. 신뢰하는 사람에게만 전달하세요. 같은 페이지는 한 명만 편집하고 다른 사용자는 커서·선택 영역과 변경 내용을 실시간으로 확인합니다.</p>
      <button className="primary-action" type="button" disabled={busy} onClick={() => void run(async () => { const created = await createCloudRoom(document); remember(created.token); const assets = await uploadDocumentAssets(created.token, document); setSnapshot({ document, revision: created.revision, updatedAt: created.updatedAt, history: [{ revision: 1, createdAt: created.updatedAt }] }); setMessage(`새 공동 편집 문서를 만들고 첨부 ${assets.uploaded}개를 R2에 동기화했습니다${assets.skipped ? ` · 로컬에서 찾지 못한 첨부 ${assets.skipped}개` : ''}.`); })}><Cloud size={16} /> 새 공동 편집 문서 만들기</button>
      <label>공유 코드<input value={code} onChange={(event) => remember(event.target.value.trim())} placeholder="공유받은 코드를 붙여넣으세요" /></label>
      <div className="cloud-actions"><button className="secondary-action" type="button" disabled={!code || busy} onClick={() => void navigator.clipboard.writeText(`${location.origin}${location.pathname}?share=${encodeURIComponent(code)}`).then(() => setMessage('공동 편집 링크를 복사했습니다.'))}><Copy size={15} /> 링크 복사</button><button className="secondary-action" type="button" disabled={!code || busy} onClick={() => void run(() => refresh(false))}><RefreshCw size={15} /> 새 변경 확인</button><button className="secondary-action" type="button" disabled={!snapshot || busy} onClick={() => void run(() => refresh(true))}>클라우드판 적용</button><button className="primary-action" type="button" disabled={!code || busy} onClick={() => void run(async () => { const value = code.trim(); announceCloudCode(value, document.id); const base = snapshot ?? await loadCloudRoom(value); const assets = await uploadDocumentAssets(value, document); const pushed = await pushCloudRoom(value, base.revision, document); await refresh(false); setMessage(`${pushed.revision}판과 새 첨부 ${assets.uploaded}개를 저장했습니다.`); })}><UploadCloud size={15} /> 내 변경 저장</button></div>
      {progress && busy && <div className="cloud-upload-progress" role="status"><span>{progress.status === 'retrying' ? '재시도 중' : 'R2 무손실 동기화'} · {progress.name}</span><progress max={Math.max(1, progress.total)} value={progress.loaded} /><small>{Math.round(progress.loaded / Math.max(1, progress.total) * 100)}%</small></div>}
      {message && <p className={`dialog-message ${failed ? 'error' : 'success'}`}>{message}</p>}
      {snapshot && <div className="version-history"><h3><History size={16} /> 버전 이력</h3>{snapshot.history.map((version) => <div key={version.revision}><span><strong>{version.revision}판</strong><small>{new Date(version.createdAt).toLocaleString('ko-KR')}</small></span><button type="button" onClick={() => void run(async () => { const result = await loadCloudVersion(code, version.revision); await hydrateDocumentAssets(code, result.document); announceCloudCode(code, result.document.id); onChange(result.document); setMessage(`${version.revision}판과 R2 첨부를 편집 화면에 복원했습니다. 클라우드에 확정하려면 ‘내 변경 저장’을 누르세요.`); })}>이 버전 열기</button></div>)}</div>}
    </div>
  </section></div>;
}
